[project]
name = "to-do-flask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "flask-pydantic>=0.14.0",
    "flask-sqlalchemy-lite>=0.2.1",
]
